# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This is a example documentation
#' It looks like this
#' make sure you have the 'export' to make the function reachable from R (look at what happens at  R/RcppExports.R)
#' @export
display_constants <- function() {
    invisible(.Call('_Rfgc_display_constants', PACKAGE = 'Rfgc'))
}

display_sse_info <- function() {
    invisible(.Call('_Rfgc_display_sse_info', PACKAGE = 'Rfgc'))
}

display_samplers <- function() {
    invisible(.Call('_Rfgc_display_samplers', PACKAGE = 'Rfgc'))
}

construct_coresetdd <- function(X, k, cs_size, measure = 1L, sampler = 4L, seed = 0L) {
    .Call('_Rfgc_construct_coresetdd', PACKAGE = 'Rfgc', X, k, cs_size, measure, sampler, seed)
}

construct_coresetdf <- function(X, k, cs_size, measure = 1L, sampler = 4L, seed = 0L) {
    .Call('_Rfgc_construct_coresetdf', PACKAGE = 'Rfgc', X, k, cs_size, measure, sampler, seed)
}

construct_coresetsd <- function(X, k, cs_size, measure = 1L, sampler = 4L, seed = 0L) {
    .Call('_Rfgc_construct_coresetsd', PACKAGE = 'Rfgc', X, k, cs_size, measure, sampler, seed)
}

construct_coresetsf <- function(X, k, cs_size, measure = 1L, sampler = 4L, seed = 0L) {
    .Call('_Rfgc_construct_coresetsf', PACKAGE = 'Rfgc', X, k, cs_size, measure, sampler, seed)
}

kmeans_coresetdd <- function(X, k, cs_size, seed = 0L) {
    .Call('_Rfgc_kmeans_coresetdd', PACKAGE = 'Rfgc', X, k, cs_size, seed)
}

kmeans_coresetdf <- function(X, k, cs_size, seed = 0L) {
    .Call('_Rfgc_kmeans_coresetdf', PACKAGE = 'Rfgc', X, k, cs_size, seed)
}

kmeans_coresetsd <- function(X, k, cs_size, seed = 0L) {
    .Call('_Rfgc_kmeans_coresetsd', PACKAGE = 'Rfgc', X, k, cs_size, seed)
}

kmeans_coresetsf <- function(X, k, cs_size, seed = 0L) {
    .Call('_Rfgc_kmeans_coresetsf', PACKAGE = 'Rfgc', X, k, cs_size, seed)
}

dist_matrixdd <- function(X, arg, gamma_beta = -1) {
    .Call('_Rfgc_dist_matrixdd', PACKAGE = 'Rfgc', X, arg, gamma_beta)
}

dist_matrixdf <- function(X, arg, gamma_beta = -1) {
    .Call('_Rfgc_dist_matrixdf', PACKAGE = 'Rfgc', X, arg, gamma_beta)
}

dist_matrixsd <- function(X, arg, gamma_beta = -1) {
    .Call('_Rfgc_dist_matrixsd', PACKAGE = 'Rfgc', X, arg, gamma_beta)
}

dist_matrixsf <- function(X, arg, gamma_beta = -1) {
    .Call('_Rfgc_dist_matrixsf', PACKAGE = 'Rfgc', X, arg, gamma_beta)
}

llr_matrixdd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_llr_matrixdd', PACKAGE = 'Rfgc', X, gamma_beta)
}

llr_matrixdf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_llr_matrixdf', PACKAGE = 'Rfgc', X, gamma_beta)
}

llr_matrixsd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_llr_matrixsd', PACKAGE = 'Rfgc', X, gamma_beta)
}

llr_matrixsf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_llr_matrixsf', PACKAGE = 'Rfgc', X, gamma_beta)
}

uwllr_matrixdd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_uwllr_matrixdd', PACKAGE = 'Rfgc', X, gamma_beta)
}

uwllr_matrixdf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_uwllr_matrixdf', PACKAGE = 'Rfgc', X, gamma_beta)
}

uwllr_matrixsd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_uwllr_matrixsd', PACKAGE = 'Rfgc', X, gamma_beta)
}

uwllr_matrixsf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_uwllr_matrixsf', PACKAGE = 'Rfgc', X, gamma_beta)
}

jsd_matrixdd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_jsd_matrixdd', PACKAGE = 'Rfgc', X, gamma_beta)
}

jsd_matrixdf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_jsd_matrixdf', PACKAGE = 'Rfgc', X, gamma_beta)
}

jsd_matrixsd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_jsd_matrixsd', PACKAGE = 'Rfgc', X, gamma_beta)
}

jsd_matrixsf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_jsd_matrixsf', PACKAGE = 'Rfgc', X, gamma_beta)
}

jsm_matrixdd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_jsm_matrixdd', PACKAGE = 'Rfgc', X, gamma_beta)
}

jsm_matrixdf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_jsm_matrixdf', PACKAGE = 'Rfgc', X, gamma_beta)
}

jsm_matrixsd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_jsm_matrixsd', PACKAGE = 'Rfgc', X, gamma_beta)
}

jsm_matrixsf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_jsm_matrixsf', PACKAGE = 'Rfgc', X, gamma_beta)
}

l2_matrixdd <- function(X) {
    .Call('_Rfgc_l2_matrixdd', PACKAGE = 'Rfgc', X)
}

l2_matrixdf <- function(X) {
    .Call('_Rfgc_l2_matrixdf', PACKAGE = 'Rfgc', X)
}

l2_matrixsd <- function(X) {
    .Call('_Rfgc_l2_matrixsd', PACKAGE = 'Rfgc', X)
}

l2_matrixsf <- function(X) {
    .Call('_Rfgc_l2_matrixsf', PACKAGE = 'Rfgc', X)
}

l1_matrixdd <- function(X) {
    .Call('_Rfgc_l1_matrixdd', PACKAGE = 'Rfgc', X)
}

l1_matrixdf <- function(X) {
    .Call('_Rfgc_l1_matrixdf', PACKAGE = 'Rfgc', X)
}

l1_matrixsd <- function(X) {
    .Call('_Rfgc_l1_matrixsd', PACKAGE = 'Rfgc', X)
}

l1_matrixsf <- function(X) {
    .Call('_Rfgc_l1_matrixsf', PACKAGE = 'Rfgc', X)
}

sqrl2_matrixdd <- function(X) {
    .Call('_Rfgc_sqrl2_matrixdd', PACKAGE = 'Rfgc', X)
}

sqrl2_matrixdf <- function(X) {
    .Call('_Rfgc_sqrl2_matrixdf', PACKAGE = 'Rfgc', X)
}

sqrl2_matrixsd <- function(X) {
    .Call('_Rfgc_sqrl2_matrixsd', PACKAGE = 'Rfgc', X)
}

sqrl2_matrixsf <- function(X) {
    .Call('_Rfgc_sqrl2_matrixsf', PACKAGE = 'Rfgc', X)
}

mkl_matrixdd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_mkl_matrixdd', PACKAGE = 'Rfgc', X, gamma_beta)
}

mkl_matrixdf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_mkl_matrixdf', PACKAGE = 'Rfgc', X, gamma_beta)
}

mkl_matrixsd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_mkl_matrixsd', PACKAGE = 'Rfgc', X, gamma_beta)
}

mkl_matrixsf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_mkl_matrixsf', PACKAGE = 'Rfgc', X, gamma_beta)
}

tvd_matrixdd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_tvd_matrixdd', PACKAGE = 'Rfgc', X, gamma_beta)
}

tvd_matrixdf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_tvd_matrixdf', PACKAGE = 'Rfgc', X, gamma_beta)
}

tvd_matrixsd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_tvd_matrixsd', PACKAGE = 'Rfgc', X, gamma_beta)
}

tvd_matrixsf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_tvd_matrixsf', PACKAGE = 'Rfgc', X, gamma_beta)
}

bhattacharyya_metric_matrixdd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_bhattacharyya_metric_matrixdd', PACKAGE = 'Rfgc', X, gamma_beta)
}

bhattacharyya_metric_matrixdf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_bhattacharyya_metric_matrixdf', PACKAGE = 'Rfgc', X, gamma_beta)
}

bhattacharyya_metric_matrixsd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_bhattacharyya_metric_matrixsd', PACKAGE = 'Rfgc', X, gamma_beta)
}

bhattacharyya_metric_matrixsf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_bhattacharyya_metric_matrixsf', PACKAGE = 'Rfgc', X, gamma_beta)
}

bhattacharyya_distance_matrixdd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_bhattacharyya_distance_matrixdd', PACKAGE = 'Rfgc', X, gamma_beta)
}

bhattacharyya_distance_matrixdf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_bhattacharyya_distance_matrixdf', PACKAGE = 'Rfgc', X, gamma_beta)
}

bhattacharyya_distance_matrixsd <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_bhattacharyya_distance_matrixsd', PACKAGE = 'Rfgc', X, gamma_beta)
}

bhattacharyya_distance_matrixsf <- function(X, gamma_beta = -1) {
    .Call('_Rfgc_bhattacharyya_distance_matrixsf', PACKAGE = 'Rfgc', X, gamma_beta)
}

